name: Web Almas

on: 
    push:
        branches:
            - lab7
    pull_request:
        branches:
            - lab7

jobs:
    test:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2
                architecture: X64
                cache: false
            - run: flutter pub get
            - run: flutter test test/test.dart
            - run: flutter analyze  --no-fatal-warnings --no-fatal-infos lib/templates/lab7/ 
            - run: flutter build web --release --base-href='/Sum24FlutterCourse/' lib/templates/lab7/main.dart
            - uses: bluefireteam/flutter-gh-pages@v7
              with:
                base-href: /Sum24FlutterCourse/
                customArgs: "lib/templates/lab7/main.dart"